name:                sisyphus-robot-browser
version:             0.1.0.0
github:              "Zankoku-Okuno/sisyphus-robot-browser"
license:             BSD3
author:              "Okuno Zankoku"
maintainer:          "zankoku.okuno@gmail.com"
copyright:           "Okuno Zankoku"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Zankoku-Okuno/sisyphus-robot-browser#readme>

dependencies:
- base >= 4.7 && < 5
- sisyphus-robot-common
- aeson ==1.*
- text ==1.*
- reflex ==0.5.*
- reflex-dom ==0.4.*
# TODO - servant-reflex ==0.3.4, once I'm using reflex 0.5

default-extensions:
- OverloadedStrings
- RecordWildCards
- RecursiveDo
- ScopedTypeVariables
- FlexibleContexts
- TypeFamilies

library:
  source-dirs: src

executables:
  sisyphus-robot-browser:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sisyphus-robot-browser

tests:
  sisyphus-robot-browser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sisyphus-robot-browser
